# Generated by Django 5.2.3 on 2025-06-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
